### ISSUE TITLE
Fails to parse 6+0*8 properly -- yields 48 not 6

### ISSUE THREAD

**Issue by wasbridge** [bpowers/sd.js#1]
This patch fixes the issue by constructing the RHS of a binary operator by restarting the search at level 0 and stoping at the current level

[0001-PEMDAS-fix-6-0-8.txt](https://github.com/bpowers/sd.js/files/1786375/0001-PEMDAS-fix-6-0-8.txt)

**Comment by bpowers** [comment]
applied
